Bring library code up to php 7.4 standards
paysera/lib-webtopay pull request #25
Opened 2024-04-30 08:19 UTC by oleksandr-gribiennikov-paysera

2024-05-01 08:02 UTC, alexanderzaiets-paysera requested changes

2024-05-02 06:29 UTC, oleksandr-gribiennikov-paysera commented on tests/StaticMethods/FactoryTest.php
> +    protected function tearDown(): void
done

2024-05-02 06:31 UTC, oleksandr-gribiennikov-paysera commented on src/WebToPay/UrlBuilder.php
> +     * @codeCoverageIgnore We do not support sms-service anymore
done

2024-05-02 06:32 UTC, oleksandr-gribiennikov-paysera commented on src/WebToPay/SmsAnswerSender.php
> +     * @codeCoverageIgnore We do not support sms-service anymore
done

2024-05-02 08:21 UTC, merged